### ISSUE TITLE
crash in Chrome when col width is set to 12

### ISSUE THREAD

**Issue by innerop** [domenic/rewrapper#1]
Column width was set to 120, and I removed the 0. It narrowed it to one word per row but after 3-5 seconds the browser crashed.

<img width="1291" alt="Screen Shot 2020-01-21 at 2 31 03 PM" src="https://user-images.githubusercontent.com/43629788/72849064-cd75e400-3c5a-11ea-8f2c-67b369ec1be5.png">

**Comment by domenic** [comment]
I believe this was fixed by https://github.com/domenic/rewrapper/commit/01c0df1a6730a612e2192eb6ff62b2b69338d5d9.
