### ISSUE TITLE
Line not handled correctly

### ISSUE THREAD

**Issue by domfarolino** [domenic/rewrapper#4]
For some reason (I haven't looked closely at the code in a while), the rewrapper wraps the following line (104 characters):

```html
  data-x="opener policy">opener policies</span> <var>accessorCOOP</var> and <var>accessedCOOP</var>, foo
```

to the following:

```html
  data-x="opener policy">opener policies</span> <var>accessorCOOP</var> and
  <var>accessedCOOP</var>, foo
```

... which is a suboptimal wrap. I think it should be:

```html
  data-x="opener policy">opener policies</span> <var>accessorCOOP</var> and <var>accessedCOOP</var>,
  foo
```

... which is what [`specfmt`](https://github.com/domfarolino/specfmt) yields. In any case, maybe we could link to specfmt from this tool since I think it's quite useful, as it can operate directly on HTML PRs and scope its changes to an entire branch diff.

**Comment by domenic** [comment]
I've noticed similar issues. I think it's an off-by-one error, probably in this tool.
